env:
  browser: true
  es2021: true

extends:
  - "plugin:react/recommended"
  - "airbnb"
  - "plugin:import/errors"
  - "plugin:import/warnings"
  - "plugin:import/typescript"
  - "plugin:@typescript-eslint/eslint-recommended"
  - "plugin:@typescript-eslint/recommended"

parser: "@typescript-eslint/parser"

parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 12
  sourceType: module

plugins:
  - "react"
  - "@typescript-eslint"
  - "import"

rules:
  {
    "@typescript-eslint/no-use-before-define": ["error"],
    "quotes": ["error", "double"],
    "class-methods-use-this": ["error"],
    "react/react-in-jsx-scope": "off",
    "import/no-unresolved": "off",
    "import/extensions": "off",
    "no-use-before-define": "off",
    "react/jsx-filename-extension": ["error", { "extensions": [".js", ".jsx", ".ts", ".tsx"] }],
    "sort-imports": 0,
    "import/order": [2, { "alphabetize": { "order": "asc" } }],
    "react/jsx-one-expression-per-line": 0,
  }
