name: github pages

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      # Checkout
      - uses: actions/checkout@v2
      
      # Setup Node
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
          
      # Build
      - name: Build pages
        run: |
          npm ci
          npm run build
          npm run export
          touch ./out/.nojekyll
        env:
          GITHUB_PAGES: ${{ github.ref == 'refs/heads/main' }}
          CI: ${{ true }}

      # Deploy Netlify
      - name: Deploy to netlify
        if: github.event_name == 'pull_request'
        run: |
          npm install netlify-cli
          npx netlify-cli deploy --dir=./out --message="update pages." 1> deploy.log
          cat deploy.log
          cat deploy.log | grep "Website Draft URL" 1> url.log          
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
          
      # Comment
      - uses: actions/github-script@0.8.0
        if: github.event_name == 'pull_request'
        with:
          script: |
            const fs = require('fs').promises
            const content = await fs.readFile('url.log', 'utf-8')
            const regex = /[\u001b\u009b][[()#;?]*(?:[0-9]{1,4}(?:;[0-9]{0,4})*)?[0-9A-ORZcf-nqry=><]/g
            const url = content.replace(regex, "")
            console.log(url)
            
            const issueNumber = context.issue.number
            const owner = context.repo.owner
            const repo = context.repo.repo
            const text = `Deploy Completed.\n${url}`
            github.issues.createComment({ issue_number: issueNumber, owner: owner, repo: repo, body: text })
            
      # Deploy gh-pages
      - uses: peaceiris/actions-gh-pages@v3
        if: github.ref == 'refs/heads/main'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./out
